name = "ExampleJuliaPkg"
uuid = "c5d62dd9-9a75-48b9-8ae0-fca978c6590a"
authors = ["Judah Sklan"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
